name-template: 'v$INPUT_VERSION'
tag-template: 'v$INPUT_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
include-labels:
  - 'feature'
  - 'enhancement'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'chore'
template: |
  ## Changes

  $CHANGES
