---

repos:
- repo: local
  hooks:
    - id: format
      name: format
      entry: nox
      language: python
      language_version: python3
      args: ["-rs", "black", "-p", "3.9"]
      require_serial: true
      additional_dependencies: []
    - id: lint
      name: lint
      entry: nox
      language: python
      language_version: python3
      args: ["-rs", "lint", "-p", "3.9"]
      require_serial: true
      additional_dependencies: []
    - id: mypy
      name: mypy
      entry: nox
      language: python
      language_version: python3
      args: ["-rs", "mypy", "-p", "3.9"]
      require_serial: true
      additional_dependencies: []